create table if not exists public.catalog_sources (
  id bigint generated by default as identity primary key,
  csv_url text not null,
  image_base_url text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.catalog_sources enable row level security;

-- The application uses the server-only Supabase secret key.
-- Do not add a public select policy for this table.
